app:
  name: "Wahlsoftware 2"
  title: "CivicSoft Germany"
  version: "1.0.0"
  organization: "CivicSoft Germany"
  domain: "civicsoft.de"

window:
  width: 1280
  height: 720
  min_width: 1280
  min_height: 720
  icon: ":/static/icons/chart2.ico"

features:
  debug: true
  logging: true

pkcs11:
  conf: "C:/SoftHSM2/etc/softhsm2.conf"
  lib: "C:/SoftHSM2/lib/softhsm2-x64.dll"