routes:
  # Auth
  auth_index: "AuthController::index"
  auth_login: "AuthController::login"

  # Election
  election_index: "ElectionController::index"
  election_add: "ElectionController::add_entry"

  # Start (Alias)
  start: "AuthController::index"